### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by fusichao** [postech-ami/FastMETRO#1]
Very interested in your work! How to train my own dataset or can you provide some pre training models?

**Comment by FastMETRO** [comment]
Hello, 

Our code is under refactoring. In the meantime, please refer to  [[Code Snippet (Overall Architecture)]](https://github.com/postech-ami/FastMETRO/blob/main/src/fastmetro.py) and [[Code Snippet (Transformer Encoder-Decoder)]](https://github.com/postech-ami/FastMETRO/blob/main/src/transformer.py) which contains the main framework of our FastMETRO.

The training procedure for FastMETRO is based on [METRO](https://github.com/microsoft/MeshTransformer). It would be helpful for you to check [[INSTALL]](https://github.com/microsoft/MeshTransformer/blob/main/docs/INSTALL.md), [[DOWNLOAD]](https://github.com/microsoft/MeshTransformer/blob/main/docs/DOWNLOAD.md) and [[EXP]](https://github.com/microsoft/MeshTransformer/blob/main/docs/EXP.md) provided by [METRO](https://github.com/microsoft/MeshTransformer).

We are planning to release our complete code and pre-trained models within a few months.

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
