### ISSUE TITLE
How to generate the heatmap and attention map

### ISSUE THREAD

**Issue by MooreManor** [postech-ami/FastMETRO#11]
@FastMETRO 
Can you share the script to generate the heatmap and attention maps like below for analysis?
![image](https://user-images.githubusercontent.com/49632327/207118266-69f83071-a4bb-41f1-a4b9-1f5f48a84ae9.png)![image](https://user-images.githubusercontent.com/49632327/207118308-c7586d3c-ce77-42cf-9e17-ab6092ab76c7.png)

**Comment by FastMETRO** [comment]
Hello,

The codes used to visualize attention scores are under refactoring. In the meantime, please refer to these guidelines.

---

### [ Visualization of Self-Attention Scores in Transformer Decoder ]

#### < High-level Description >

- Obtain self-attention scores in the transformer decoder 
o query: 14 joint tokens 
o key: 431 vertex tokens

- Average those scores from all attention heads of multi-head self-attention modules in all transformer decoder layers

- Visualize the averaged attention scores obtained from the queries and keys

#### < Details >

- In `src/modeling/model/transformer.py`, the multi-head self-attention module in each transformer decoder layer (`self.self_attn` in ` TransformerDecoderLayer`) is an instance of `nn.MultiheadAttention`

- In `nn.MultiheadAttention`, you can obtain averaged attention scores from all attention heads by setting `need_weights` as `True` and `average_attn_weights` as `True`
o Please refer to [MultiheadAttention](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/activation.py) and [multi_head_attention_forward](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py)

- Obtain those attention scores (`t2t_attn_weight`):
```
tgt2, t2t_attn_weight = self.self_attn(q, k, value=tgt2, attn_mask=tgt_mask,
                                       key_padding_mask=tgt_key_padding_mask, 
                                       need_weights=True,
                                       average_attn_weights=True)
```

- Average those attention scores from all transformer decoder layers

- Visualize the averaged attention scores obtained from the queries (14 joint tokens) and the keys (431 vertex tokens)
o Please refer to [visualize_reconstruction_and_att_local](https://github.com/microsoft/MeshTransformer/blob/main/metro/utils/renderer.py) in [METRO](https://github.com/microsoft/MeshTransformer)

---

### [ Visualization of Cross-Attention Scores in Transformer Decoder ]

#### < High-level Description >

- Obtain cross-attention scores in the transformer decoder
o query: 14 joint tokens
o key: 49 image features

- Average those scores from all attention heads of multi-head cross-attention modules in all transformer decoder layers

- Visualize the averaged attention scores obtained from the queries and keys

#### < Details >

- In `src/modeling/model/transformer.py`, the multi-head cross-attention module in each transformer decoder layer (`self.multihead_attn` in ` TransformerDecoderLayer`) is an instance of `nn.MultiheadAttention`

- In `nn.MultiheadAttention`, you can obtain averaged attention scores from all attention heads by setting `need_weights` as `True` and `average_attn_weights` as `True`
o Please refer to [MultiheadAttention](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/activation.py) and [multi_head_attention_forward](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py)

- Obtain those attention scores (`t2i_attn_weight`):
```
tgt2, t2i_attn_weight = self.multihead_attn(query=self.with_pos_embed(tgt2, query_pos),
                                            key=self.with_pos_embed(memory, pos),
                                            value=memory, attn_mask=memory_mask,
                                            key_padding_mask=memory_key_padding_mask,
                                            need_weights=True,
                                            average_attn_weights=True)
```

- Average those attention scores from all transformer decoder layers

- Visualize the averaged attention scores obtained from the queries (14 joint tokens) and the keys (49 image features)
o You need to perform bilinear interpolation to visualize those scores on input images

---

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
