### ISSUE TITLE
About performance difference between different `PA_MPJPE` calculation method on hands.

### ISSUE THREAD

**Issue by imabackstabber** [postech-ami/FastMETRO#12]
Hi, I adopted `reconstruction_error` function in `utils/metric_pampjpe.py` to calculate **PA_MPJPE** metric on hands(which is originally used for body, in the repo)., and I'm pretty sure the result is **aligned**(i.e. substract the position of `Wrist`)
But the result is inferior to the de-facto standard when calculating `PA_MPJPE` for hands, which is written in the code given: saving results as `pred.json` and using `eval.py` in [freihand](https://github.com/lmb-freiburg/freihand) to calucalate align result(and that will be the final `PA_MPJPE`, to my knowledge).
The result `reconstruction_error` given is roughly `24~25`mm, however, the `pred.json` method mentioned above says that result is about `6~7`mm. The huge difference bothers me.
Could you please explain the reason why the two methods given differ so much? Your reply will be highly appreciated.

**Comment by FastMETRO** [comment]
Hello,

For the evaluation, we used the [official evaluation code](https://github.com/lmb-freiburg/freihand/blob/master/eval.py) provided by [FreiHAND](https://github.com/lmb-freiburg/freihand). If you want to merge the evaluation code with our repository, please check these guidelines.

---

- The [official evaluation annotations](https://lmb.informatik.uni-freiburg.de/resources/datasets/FreihandDataset.en.html) should be correctly loaded. In `freihand.tar`, evaluation annotations are filled with dummy values. At the time when [METRO](https://github.com/microsoft/MeshTransformer) released `freihand.tar`, the [official evaluation annotations](https://lmb.informatik.uni-freiburg.de/resources/datasets/FreihandDataset.en.html) were not accessible. Please refer to lines 211-215 of [tsv_demo_freihand.py](https://github.com/microsoft/MeshTransformer/blob/main/metro/tools/tsv_demo_freihand.py) in [METRO](https://github.com/microsoft/MeshTransformer).

- The 3D hand outputs should be correctly aligned. Please refer to `compute_similarity_transform()` in `src/utils/metric_pampjpe.py` and `align_w_scale()` in the [official evaluation code](https://github.com/lmb-freiburg/freihand/blob/master/eval.py).

---

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.

**Comment by imabackstabber** [comment]
Thanks! That really helps with my problem!

**Comment by FastMETRO** [comment]
Glad to hear that our guidelines resolved your issue :)
