### ISSUE TITLE
About pretrained CNN network

### ISSUE THREAD

**Issue by Hao-hui** [postech-ami/FastMETRO#14]
In PARE(ICCV2021) and a number of other articles, they mentioned that training ResNet or HR-Net with attitude estimation task on COCO dataset can help improve the performance of human reconstruction network. However, it seems that in your experiment, the network was pre-trained with image-net. Have you done any relevant experiments？

**Comment by FastMETRO** [comment]
Hello,

For the fair comparison with [METRO](https://github.com/microsoft/MeshTransformer), we used the same backbone initialized with the same pre-trained weights (i.e., pre-trained with ImageNet). We haven’t conducted experiments on the different backbone initialization with other pre-trained weights (e.g., pre-trained with COCO). 

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
