### ISSUE TITLE
FLOPs 

### ISSUE THREAD

**Issue by vatsalag99** [postech-ami/FastMETRO#15]
Hi, Thanks for this work. I wanted to ask how you calculated the FLOPs for each of your models and if there was a particular library you used.

**Comment by FastMETRO** [comment]
Hello,

One could estimate FLOPs for PyTorch operators or modules using [fvcore](https://github.com/facebookresearch/fvcore), [thop](https://github.com/Lyken17/pytorch-OpCounter), or [ptflops](https://github.com/sovrasov/flops-counter.pytorch) libraries. Note that some libraries do not count FLOPs for particular operators (e.g., ```torch.nn.functional.*``` operators when using [ptflops](https://github.com/sovrasov/flops-counter.pytorch) library) and for custom modules if you do not implement or register corresponding FLOPs counters. Please refer to those libraries for more details.

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
