### ISSUE TITLE
About DDP train on the specified gpu

### ISSUE THREAD

**Issue by xuchuyanglove** [postech-ami/FastMETRO#17]
Hello, I am very interested in your work, but I have encountered some difficulties in running the project. I want to know whether I can specify some gpus on a single-machine multi-card server to train your model.
  For example, my server is a server with 8 RTX 3080 gpus. So can I distributed train your model with only the index 4 gpu and the index 7 gpu.
  Thank you very much.

**Comment by FastMETRO** [comment]
Hello, 

You could select GPU indexes <1> on the bash script (using ```CUDA_VISIBLE_DEVICES=4,7```) or <2> inside the main code (using ```torch.cuda.set_device(torch.device(“cuda:4,7”))``` or ```os.environ["CUDA_VISIBLE_DEVICES"] = "4,7"```).

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.

**Comment by xuchuyanglove** [comment]
Thank you very much. Actually, I found a solution on blog later, which is consistent with the solution you described. 
So I closed this issue.Your work is great, and thank you very much again

> Hello,
> 
> You could select GPU indexes <1> on the bash script (using `CUDA_VISIBLE_DEVICES=4,7`) or <2> inside the main code (using `torch.cuda.set_device(torch.device(“cuda:4,7”))` or `os.environ["CUDA_VISIBLE_DEVICES"] = "4,7"`).
> 
> Thanks for your interest in our work!!
