### ISSUE TITLE
can you provide me your position_encoding.py? thx

### ISSUE THREAD

**Issue by langyan1-tal** [postech-ami/FastMETRO#2]

**Comment by FastMETRO** [comment]
Hello,

Now, you can check our [[position_encoding.py]](https://github.com/postech-ami/FastMETRO/blob/main/src/position_encoding.py).

We employ the positional encodings provided by [DETR](https://github.com/facebookresearch/detr). 

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
