### ISSUE TITLE
Question about the option "use_smpl_param_regressor"

### ISSUE THREAD

**Issue by PassionTree** [postech-ami/FastMETRO#20]
Thank you for your awesome research!
What is the difference whether using the option "use_smpl_param_regressor"?

**Comment by FastMETRO** [comment]
Hello,

If ```--use_smpl_param_regressor``` option is set to ```True```, then a SMPL parameter regressor would regress SMPL parameters from the output mesh vertices estimated by FastMETRO. Please refer to [Experiments.md](https://github.com/postech-ami/FastMETRO/blob/main/docs/Experiments.md) and [Section C of the supplementary material](https://arxiv.org/abs/2207.13820) for more details.

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
