### ISSUE TITLE
FLOPs of the model

### ISSUE THREAD

**Issue by mimiliaogo** [postech-ami/FastMETRO#22]
Would you like to provide the FLOPs of your small, middle, and large models? 
Thanks!

**Comment by FastMETRO** [comment]
Hello,

Please refer to [Table 2 of POTTER](https://arxiv.org/abs/2303.13357) or [Table 2 of FeatER](https://arxiv.org/abs/2205.15448) or [Table 2 of TORE](https://arxiv.org/abs/2211.10705).

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
