### ISSUE TITLE
Script for reorganizing data set?

### ISSUE THREAD

**Issue by moonsh** [postech-ami/FastMETRO#23]
I wonder how TSV files are generated.

Could you share the script for generating the dataset?

**Comment by gahahaaA** [comment]
> 我想知道 TSV 文件是如何生成的。
> 
> 您能分享一下生成数据集的脚本吗？

cd $REPO_DIR
path/to/azcopy copy 'https://datarelease.blob.core.windows.net/metro/datasets/filename.tar' /path/to/your/folder/filename.tar
tar xvf filename.tar 
Have you successfully downloaded filename.tar？

**Comment by FastMETRO** [comment]
Hello,

[METRO](https://github.com/microsoft/MeshTransformer) provides the code used for producing tsv files. Please refer to [MeshTransformer/metro/tools/tsv_demo_h36m.py](https://github.com/microsoft/MeshTransformer/blob/main/metro/tools/tsv_demo_h36m.py)

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
