### ISSUE TITLE
Attention mask and global attention

### ISSUE THREAD

**Issue by Dariushuangg** [postech-ami/FastMETRO#26]
Hi, in your code, an attention mask is applied to prevent non-adjacent vertex to attend to each other. However, in your visualization, there are strong attention score between non-adjacent vertices like between right wrist and head. Since the visualization code is not yet available, could you explain why would the said situation happen? This might be a dumb question but still hope to get an answer. Thx so much in advanced!! 
![image](https://github.com/postech-ami/FastMETRO/assets/111829337/173f53ab-4cd4-4eb8-8c12-f57912dba8b5)

**Comment by FastMETRO** [comment]
Hello,

The proposed method only masks self-attentions of non-adjacent vertices. In other words, it allows self-attentions between joints and vertices. The figure visualizes the attention scores in self-attentions between a specific body joint (ie., right wrist) and vertices.

For the visualization, please refer to [Issue #11](https://github.com/postech-ami/FastMETRO/issues/11)

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.

**Comment by Dariushuangg** [comment]
Oh I see! This answers my question. Thanks!!
