### ISSUE TITLE
Linked model licensing

### ISSUE THREAD

**Issue by robinsonkwame** [postech-ami/FastMETRO#29]
Just wanted to clarify that the trained non-parametric models and src/data/*.pt files are MIT licensed since the repository contains an MIT license.

**Comment by FastMETRO** [comment]
Hello,

Our research code is released under the MIT license. For our pre-trained model weights (e.g., FastMETRO-S-R50_h36m_state_dict.bin), you could utilize them for research purposes without limitations. 

However, for other data (e.g., SMPL, MANO, Manopth) used in our experiments, you should carefully follow their licenses (e.g., [SMPL-Model License](https://smpl.is.tue.mpg.de/modellicense.html), [MANO License](https://mano.is.tue.mpg.de/license.html), [Manopth License](https://github.com/hassony2/manopth/blob/master/LICENSE)) as described in [License](https://github.com/postech-ami/FastMETRO#license).

Thanks for your interest in our work!!

**Comment by robinsonkwame** [comment]
Thanks for the reply! 

Just so I’m clear, the pre-trained model weights can be used without limitation for commercial research purposes? Some research is in industry which is why I ask.

(edited for clarity)

**Comment by FastMETRO** [comment]
Yes, you could use our pre-trained model weights for commercial research purposes without limitations. 

Following the MIT license, we are not liable for any damages or issues arising from its use. Also, you should include the original copyright and license notice.

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
