### ISSUE TITLE
Training args?

### ISSUE THREAD

**Issue by Frank-Dz** [postech-ami/FastMETRO#5]
I understand that this code repo is under development.
Could you simply tell me the training args 
```
 self.transformer_config_1 = {"model_dim": args.model_dim_1, "dropout": args.transformer_dropout, "nhead": args.transformer_nhead, 
                                     "feedforward_dim": args.feedforward_dim_1, "num_enc_layers": num_enc_layers, "num_dec_layers": num_dec_layers, 
                                     "pos_type": args.pos_type}
        # configurations for the second transformer
        self.transformer_config_2 = {"model_dim": args.model_dim_2, "dropout": args.transformer_dropout, "nhead": args.transformer_nhead,
                                     "feedforward_dim": args.feedforward_dim_2, "num_enc_layers": num_enc_layers, "num_dec_layers": num_dec_layers, 
                                     "pos_type": args.pos_type}

...
        self.conv_1x1 = nn.Conv2d(args.conv_1x1_dim, self.transformer_config_1["model_dim"], kernel_size=1)


```
for network training?

Thanks!

**Comment by FastMETRO** [comment]
Hello,

Please refer to the arguments described as below:

```
    parser.add_argument("--model_name", default='FastMETRO_L', type=str)
    parser.add_argument("--model_dim_1", default=512, type=int)
    parser.add_argument("--model_dim_2", default=128, type=int)
    parser.add_argument("--feedforward_dim_1", default=2048, type=int)
    parser.add_argument("--feedforward_dim_2", default=512, type=int)
    parser.add_argument("--conv_1x1_dim", default=2048, type=int)
    parser.add_argument("--transformer_dropout", default=0.1, type=float)
    parser.add_argument("--transformer_nhead", default=8, type=int)
    parser.add_argument("--pos_type", default='sine', type=str)
```

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.

**Comment by Frank-Dz** [comment]
Hi~ I am trying to reproduce the result of Fastmetro using HRNET64.
I suppose you are using the same backbone in MeshGraphomer.

https://github.com/microsoft/MeshGraphormer/blob/27f7cdb33d2ce9e77969352e71a4e84eb5d9a522/src/modeling/bert/e2e_body_network.py#L56

So you are using grid feature only, am I right?
![image](https://user-images.githubusercontent.com/55009565/194299906-840273fd-fc31-4b50-bde4-c91c36687db8.png)

**Comment by FastMETRO** [comment]
Hello,

Our code is based on [METRO](https://github.com/microsoft/MeshTransformer). [METRO](https://github.com/microsoft/MeshTransformer) and [Mesh Graphormer](https://github.com/microsoft/MeshGraphormer) have subtle differences in the implementation of CNN backbone.
 
Our CNN backbone extracts image features whose shape is “Batch_Size X 2048 X 7 X 7”.

```
# extract image features through a CNN backbone
img_features = self.backbone(images) # Batch_Size X 2048 X 7 X 7
```
