### ISSUE TITLE
About 3dpw evaluation

### ISSUE THREAD

**Issue by shaohua-pan** [postech-ami/FastMETRO#6]
Hi! Thanks for the good job!
I have some quetion about how you test the  3dpw dataset on multi person sequences. Do  you use  only one person or every person one by one to evaluate?

**Comment by FastMETRO** [comment]
Hello,

If there is more than one person in an image, we would crop the image in multiple times (for a person to be located at the center in each time). In this way, we evaluate the estimation results for people one by one.

Following [METRO](https://github.com/microsoft/MeshTransformer) and [Mesh Graphormer](https://github.com/microsoft/MeshGraphormer), we crop images by using the annotations provided by [Pose2Mesh](https://github.com/hongsukchoi/Pose2Mesh_RELEASE); our model assumes that a person is located at the center of an input image.

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
