### ISSUE TITLE
About edge length loss (GT supervision) & normal vector loss

### ISSUE THREAD

**Issue by imabackstabber** [postech-ami/FastMETRO#7]
They didn't seems to be appeared in your paper. Is there any existing evaluation result when training using just 2d and 3d loss?

**Comment by FastMETRO** [comment]
Hello,

We recently added the edge length loss and normal vector loss for visually pleasing mesh results. As reported in Table 14 of [Pose2Mesh](https://arxiv.org/abs/2008.09047), those loss functions have nearly no effect on quantitative results.  

Note that the evaluation results in our paper were produced without using those loss functions.

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
