### ISSUE TITLE
Do you have plans to release mano rotmat regression as  like smpl regression?

### ISSUE THREAD

**Issue by xiaoyang333** [postech-ami/FastMETRO#9]
or you have mano regression model?

**Comment by FastMETRO** [comment]
Hello,

We don’t have any plans to implement an optional MANO parameter regressor.

For the implementation, please refer to our implementation of the SMPL parameter regressor in `src/modeling/model/smpl_param_regressor.py`.

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
